dmc_crud_homepage:
    path:     /
    defaults: { _controller: DMCCrudBundle:Ressources:index }


dmc_crud_ressources:
    path:     /ressources
    defaults: { _controller: DMCCrudBundle:Ressources:view }